{
 "title": "EMR on EKS - Spark Workload Dashboard",
 "description": "Monitors spark metrics using Prometheus in Kubernetes",
 "tags": [ "kubernetes" ],
 "time": { "from": "2021-11-08T21:06:13.072Z", "to": "2021-11-09T01:24:45.114Z" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data Source", "query": "prometheus" },
   { "name": "c_arn", "label": "Cluster ARN", "query": { "query": "kube_node_info{}" } },
   { "name": "vc_id", "label": "Virtual Cluster ID", "query": { "query": "spark_info" } },
   { "name": "job_id", "label": "Job ID", "query": { "query": "spark_info{}" } },
   {
    "name": "Pod",
    "label": "Driver ID",
    "query": {
     "query": "spark_info{emr_containers_amazonaws_com_job_id=\"$job_id\",emr_containers_amazonaws_com_virtual_cluster_id=\"$vc_id\"}"
    }
   },
   {
    "name": "executor",
    "label": "Executor ID",
    "query": {
     "query": "kube_pod_info{created_by_name=\"$Pod\"}"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "kube_pod_info{created_by_name=\"$Pod\"}"
    }
   },
   {
    "name": "Pod_ip",
    "query": {
     "query": "kube_pod_info{pod=\"$Pod\"}"
    }
   },
   {
    "name": "phase",
    "query": {
     "query": "kube_pod_status_phase{pod=~\"$Pod\"}"
    }
   },
   {
    "name": "driver_node",
    "query": {
     "query": "kube_pod_info{pod=\"$Pod\",node!=\"\"}"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": { "query": "kube_namespace_labels" } },
   { "name": "spark_version", "query": { "query": "spark_info{}" } },
   { "name": "driver_ns", "query": { "query": "spark_info{}" } },
   {
    "name": "job_runner_pod",
    "query": {
     "query": "label_values(kube_pod_info{created_by_kind=\"Job\",created_by_name=\"$job_id\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod State Timelines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Phase State Timeline",
   "type": "state-timeline",
   "description": "The phase state timeline of all job pods (driver, executor(s) and job-runner)\n\nIf this graph looks convoluted, try selecting  less executors as it can only show so many pods at a time",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "scalar(kube_pod_status_phase{pod=\"$Pod\", phase=\"Failed\"}*5) + \nscalar(kube_pod_status_phase{pod=\"$Pod\", phase=\"Pending\"}*3) + \nscalar(kube_pod_status_phase{pod=\"$Pod\", phase=\"Running\"}*2) + \nscalar(kube_pod_status_phase{pod=\"$Pod\", phase=\"Succeeded\"}*4) + scalar(kube_pod_status_phase{pod=\"$Pod\", phase=\"Unknown\"}*1)",
     "legendFormat": "Driver"
    },
    {
     "expr": "label_replace(\n(\n(\n(sum(kube_pod_status_phase{pod=~\"$executor\",phase=\"Pending\"}*3)by(pod)) + (sum(kube_pod_status_phase{pod=~\"$executor\",phase=\"Running\"}*2)by(pod)) +\n(sum(kube_pod_status_phase{pod=~\"$executor\",phase=\"Succeeded\"}*4)by(pod)) +\n(sum(kube_pod_status_phase{pod=~\"$executor\",phase=\"Unknown\"}*1)by(pod)) +\n(sum(kube_pod_status_phase{pod=~\"$executor\",phase=\"Failed\"}*5)by(pod))\n)\nand on (pod)\nkube_pod_info{created_by_name=\"$Pod\"}\n),\"executor_id\",\"$1\",\"pod\", \".*-exec-(.*)\"\n)\n>0\n",
     "legendFormat": "Executor: {{executor_id}}"
    },
    {
     "expr": "scalar(kube_pod_status_phase{pod=\"$job_runner_pod\", phase=\"Failed\"}*5) + \nscalar(kube_pod_status_phase{pod=\"$job_runner_pod\", phase=\"Pending\"}*3) + \nscalar(kube_pod_status_phase{pod=\"$job_runner_pod\", phase=\"Running\"}*2) + \nscalar(kube_pod_status_phase{pod=\"$job_runner_pod\", phase=\"Succeeded\"}*4) + scalar(kube_pod_status_phase{pod=\"$job_runner_pod\", phase=\"Unknown\"}*1)",
     "legendFormat": "JobRunner"
    }
   ]
  },
  {
   "title": "Metric Ingestion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs in Virtual Cluster",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(count(spark_info{emr_containers_amazonaws_com_virtual_cluster_id=\"$vc_id\"}>0)by(emr_containers_amazonaws_com_job_id))>0",
       "legendFormat": "Job: {{emr_containers_amazonaws_com_job_id}}"
      }
     ]
    },
    {
     "title": "Metric Ingestion",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "kube_pod_info{created_by_name=\"$job_id-spark-defaults\"}",
       "legendFormat": "EKS Metrics"
      },
      {
       "expr": "spark_info{emr_containers_amazonaws_com_job_id=\"$job_id\"}",
       "legendFormat": "Spark Metrics"
      }
     ]
    }
   ]
  },
  { "title": "Driver Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Driver IP Address",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "repeat": "Pod",
   "options": { "content": "# $Pod_ip" }
  },
  {
   "title": "Requested Driver Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{container=\"spark-kubernetes-driver\",pod=\"$Pod\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Requested Driver Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_requests{container=\"spark-kubernetes-driver\",pod=\"$Pod\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Driver Status",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{pod=\"$Pod\"}>0",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  { "title": "Driver CPU / Memory  usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Driver Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "repeat": "Pod",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\navg(container_memory_working_set_bytes{pod=\"$Pod\",container!=\"\",container!=\"POD\"}) /\navg(container_spec_memory_limit_bytes{pod=\"$Pod\",container!=\"\",container!=\"POD\"})\n)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Driver CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"^$Pod$\"} [5m])) by (pod) ",
     "legendFormat": "Used CPU : {{pod}}"
    },
    {}
   ]
  },
  { "title": "Executor CPU /Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Executor :  Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(\n(avg(container_memory_working_set_bytes{pod!=\"\",pod=~\"$executor\",container!=\"POD\",container!=\"\"})by (pod)) / on (pod)\n(avg(container_spec_memory_limit_bytes{pod!=\"\",pod=~\"$executor\",container!=\"POD\",container!=\"\"})by (pod))\nand on (pod) kube_pod_info{created_by_name=\"$Pod\"}\n) by (pod)"
    }
   ]
  },
  {
   "title": "Executor  :  CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$executor\",pod!=\"\"} [4m]) and on (pod) kube_pod_info{created_by_name=\"$Pod\"}) by (pod) ",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Network IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Driver Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~'$Pod'}[2m])) by (pod)",
     "legendFormat": "{{ pod }}  Received"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~'$Pod'}[2m])) by (pod)",
     "legendFormat": "{{ pod }}  Transmitted"
    }
   ]
  },
  {
   "title": "Executor Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~'$executor',kubernetes_io_hostname=~\"$Node\"}[2m]) and on (pod) kube_pod_info{created_by_name=\"$Pod\"}) by (pod,kubernetes_io_hostname)",
     "legendFormat": "{{ pod }} {{kubernetes_io_hostname}} Transmitted"
    }
   ]
  },
  {
   "title": "Executor Network Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~'$executor',pod!=\"pod\",kubernetes_io_hostname=~\"$Node\"}[2m]) and on (pod) kube_pod_info{created_by_name=\"$Pod\"}) by (pod,kubernetes_io_hostname)",
     "legendFormat": "{{ pod }} {{kubernetes_io_hostname}}  Received"
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Disk Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\"$Pod\"}[2m])) by (pod,device)",
     "legendFormat": "{{pod }} - {{device}} Read"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\"$executor\"}[2m]) and on (pod) kube_pod_info{created_by_name=\"$Pod\"}) by (pod,device)",
     "legendFormat": "{{pod }} - {{device}} Read"
    }
   ]
  },
  {
   "title": "Disk Writes Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$executor\"}[2m]) and on (pod) kube_pod_info{created_by_name=\"$Pod\"}) by (pod,device)",
     "legendFormat": "{{pod }} - {{device}} Write"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$Pod\"}[2m])) by (pod,device)"
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((1-(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)\n/node_memory_MemTotal_bytes)\n\nand on (kubernetes_node) \nlabel_replace(kube_pod_info{node!=\"\",created_by_name=~\"$Pod\"},\"kubernetes_node\",\"$1\",\"node\", \"(.+)\"))",
     "legendFormat": "{{kubernetes_node}} - Executor"
    },
    {
     "expr": "(1-(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)\n/node_memory_MemTotal_bytes)\nand on (kubernetes_node) {kubernetes_node=\"$driver_node\"}",
     "legendFormat": "{{kubernetes_node}} - Driver"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]) ) by (cpu, kubernetes_node)) by (kubernetes_node)\nand on (kubernetes_node) \nlabel_replace(kube_pod_info{node!=\"\",created_by_name=~\"$Pod\"},\"kubernetes_node\",\"$1\",\"node\", \"(.+)\")",
     "legendFormat": "{{kubernetes_node}} - Executor"
    },
    {
     "expr": "sum(avg(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\",kubernetes_node=\"$driver_node\"}[5m]) ) by (cpu, kubernetes_node)) by (kubernetes_node))by(kubernetes_node)",
     "legendFormat": "{{kubernetes_node}} - Driver"
    }
   ]
  },
  {
   "title": "Node Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sort_desc(\nsum(\nrate(node_network_transmit_bytes_total[5m]) \nand on (kubernetes_node) \nlabel_replace(kube_pod_info{node!=\"\",created_by_name=~\"$Pod\"},\"kubernetes_node\",\"$1\",\"node\", \"(.+)\")\n)\nby (kubernetes_node)\n)",
     "legendFormat": "Node: {{kubernetes_node}} - Executor"
    },
    {
     "expr": "sort_desc(\nsum(\nrate(node_network_transmit_bytes_total{kubernetes_node=\"$driver_node\"}[5m]))by (kubernetes_node)\n)",
     "legendFormat": "Node: {{kubernetes_node}} - Driver"
    }
   ]
  },
  {
   "title": "Node Network Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sort_desc(\nsum(\nrate(node_network_receive_bytes_total[5m]) \nand on (kubernetes_node) \nlabel_replace(kube_pod_info{node!=\"\",created_by_name=~\"$Pod\",created_by_name!~\"$job_id-spark-defaults\"},\"kubernetes_node\",\"$1\",\"node\", \"(.+)\")\n)\nby (kubernetes_node)\n)",
     "legendFormat": "Node: {{kubernetes_node}} - Executor"
    },
    {
     "expr": "sort_desc(\nsum(\nrate(node_network_receive_bytes_total{kubernetes_node=\"$driver_node\"}[5m]))by (kubernetes_node)\n)",
     "legendFormat": "Node: {{kubernetes_node}} - Driver"
    }
   ]
  },
  {
   "title": "Executor Spin Up by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(count(kube_pod_info{created_by_name=\"$Pod\",node!=\"\"})by(node))",
     "legendFormat": "Node: {{node}} - Executor"
    },
    {
     "expr": "(count(kube_pod_info{pod=\"$Pod\",node!=\"\"})by(node))",
     "legendFormat": "Node: {{node}} - Driver"
    }
   ]
  },
  {
   "title": "Node Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1-avg(node_filesystem_free_bytes/node_filesystem_size_bytes)by(kubernetes_node))\nand on (kubernetes_node) \nlabel_replace(kube_pod_info{node!=\"\",created_by_name=\"$Pod\"},\"kubernetes_node\",\"$1\",\"node\", \"(.+)\")",
     "legendFormat": "Node: {{kubernetes_node}} - Executor"
    }
   ]
  },
  {
   "title": "Node Disk Reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(sum(rate(node_disk_read_bytes_total[5m]))by(kubernetes_node)) and on (kubernetes_node) \nlabel_replace(kube_pod_info{node!=\"\",created_by_name=\"$Pod\"},\"kubernetes_node\",\"$1\",\"node\", \"(.+)\")",
     "legendFormat": "Node: {{kubernetes_node}} - Executor"
    },
    {
     "expr": "(sum(rate(node_disk_read_bytes_total{kubernetes_node=\"$driver_node\"}[5m]))by(kubernetes_node))",
     "legendFormat": "Node: {{kubernetes_node}} - Driver"
    }
   ]
  },
  {
   "title": "Node Disk Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(sum(rate(node_disk_written_bytes_total[5m]))by(kubernetes_node)) and on (kubernetes_node) \nlabel_replace(kube_pod_info{node!=\"\",created_by_name=\"$Pod\"},\"kubernetes_node\",\"$1\",\"node\", \"(.+)\")",
     "legendFormat": "Node: {{kubernetes_node}} - Executor"
    },
    {
     "expr": "(sum(rate(node_disk_written_bytes_total{kubernetes_node=\"$driver_node\"}[5m]))by(kubernetes_node))",
     "legendFormat": "Node: {{kubernetes_node}} - Driver"
    }
   ]
  },
  { "title": "Stages & Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Stages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "{__name__=~\"metrics_.*_DAGScheduler_stage_runningStages_Value\",__name__=~\".*$job_id.*\"}",
     "legendFormat": "Running Stages"
    },
    {
     "expr": "{__name__=~\"metrics_.*_appStatus_stages_completedStages_Count\",__name__=~\".*$job_id.*\"}",
     "legendFormat": "Completed Stages"
    },
    {
     "expr": "{__name__=~\"metrics_.*_appStatus_stages_failedStages_Count\",__name__=~\".*$job_id.*\"}",
     "legendFormat": "Failed Stages"
    }
   ]
  },
  {
   "title": "Completed Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "metrics_executor_completedTasks_total{kubernetes_pod_name=\"$Pod\",executor_id!=\"driver\"}",
     "legendFormat": "Executor ID: {{executor_id}}"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "expr": "metrics_executor_failedTasks_total{kubernetes_pod_name=\"$Pod\",executor_id!=\"driver\"}",
     "legendFormat": "Executor ID: {{executor_id}}"
    }
   ]
  },
  {
   "title": "Current Active Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "metrics_executor_activeTasks{kubernetes_pod_name=\"$Pod\",executor_id!=\"driver\"}",
     "legendFormat": "Executor: {{executor_id}}"
    }
   ]
  },
  {
   "title": "Skipped Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "targets": [
    {
     "expr": "{__name__=~\"metrics_.*_appStatus_tasks_skippedTasks_Count\",__name__=~\".*$job_id.*\"}",
     "legendFormat": "Tasks"
    }
   ]
  },
  {
   "title": "Spark External Shuffle",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spark Shuffle Data Written",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_executor_totalShuffleWrite_bytes_total{kubernetes_pod_name=~\"$Pod\",executor_id!=\"driver\"}",
       "legendFormat": "Executor: {{executor_id}}"
      }
     ]
    },
    {
     "title": "Spark Shuffle Data Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_executor_totalShuffleRead_bytes_total{kubernetes_pod_name=~\"$Pod\",executor_id!=\"driver\"}",
       "legendFormat": "Executor: {{executor_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Heap / Non - Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_executor_JVMHeapMemory_bytes{kubernetes_pod_name=\"$Pod\"}",
       "legendFormat": "Executor: {{executor_id}}"
      },
      {
       "expr": "jvm_memory_bytes_used{kubernetes_pod=~\"^$executor$\",area=\"heap\"}",
       "legendFormat": " {{ kubernetes_pod }} "
      }
     ]
    },
    {
     "title": "JVM Off Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_executor_JVMOffHeapMemory_bytes{kubernetes_pod_name=\"$Pod\"}",
       "legendFormat": "Executor: {{executor_id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Miscellaneous Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executors Spawned",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(kube_pod_info{created_by_name=~\"$Pod\"})",
       "legendFormat": "Executor Counts "
      }
     ]
    },
    {
     "title": "Packets Dropped : Network",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_network_receive_packets_dropped_total{pod=~\"$Pod|$executor\"}",
       "legendFormat": "{{pod}} - Receive"
      },
      {
       "expr": "container_network_transmit_packets_dropped_total{pod=~\"$Pod|$executor\"}",
       "legendFormat": "{{pod}} - Transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource usage  <To Be Deleted>",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 },
   "collapsed": true,
   "panels": [
    {
     "title": "Driver Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " sum (container_memory_working_set_bytes{pod=\"$Pod\"})/\n sum(machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      },
      {}
     ]
    },
    {
     "title": "Executor Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " sum (container_memory_working_set_bytes{pod=~\"^$executor$\",pod!=\"\"}) /sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Driver Memory Used (Avg)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod=~\"^$Pod$\"})"
      }
     ]
    },
    {
     "title": "Executor Memory  (Avg)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod=~\"$executor\",pod!=\"\"})"
      }
     ]
    },
    {
     "title": "Nodes Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 7, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(count(kube_node_info{} and on (node) (sum(kube_pod_info{created_by_name=\"$Pod\"})by(node)))by(node))/\nsum(count(kube_node_info{})by(node))",
       "legendFormat": "Nodes Used Percentage"
      },
      {}
     ]
    },
    {
     "title": "Nodes in Use",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "kube_node_info * on (node) count(kube_pod_info{created_by_name=\"$Pod\"})by(node)"
      }
     ]
    },
    { "title": "Nodes in Use", "type": "table", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 } },
    {
     "title": "Node Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 3, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{container!=\"POD\",container!=\"\"} * on (pod) group_left(node) kube_pod_info{created_by_name=~\"$Pod\"})by(node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Node CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[5m]) * on (pod) group_left(node) kube_pod_info{created_by_name=~\"$Pod\"})by(node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Node Network Transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{container=\"POD\"}[5m]) * on (pod) group_left(node) kube_pod_info{created_by_name=~\"$Pod|$job_id-spark-defaults\"})by(node)",
       "legendFormat": "Node: {{node}} "
      }
     ]
    },
    {
     "title": "Node Network Transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{container=\"POD\"}[5m]) * on (pod) group_left(node) kube_pod_info{created_by_name=~\"$Pod|$job_id-spark-defaults\"})by(node)",
       "legendFormat": "Node: {{node}} "
      }
     ]
    },
    {
     "title": "Executor Status",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "count(kube_pod_status_phase{pod=~\"$executor\"}>0)by(phase)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Node Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)\nand on (kubernetes_node) \nlabel_replace(kube_pod_info{node!=\"\",created_by_name=~\"$Pod\"},\"kubernetes_node\",\"$1\",\"node\", \"(.+)\")",
       "legendFormat": "{{kubernetes_node}} - Executor"
      },
      {
       "expr": "(node_memory_MemTotal_bytes{kubernetes_node=\"$driver_node\"} - node_memory_MemAvailable_bytes  {kubernetes_node=\"$driver_node\"})\n",
       "legendFormat": "{{kubernetes_node}} - Driver"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "state-timeline",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 89 },
     "targets": [
      {
       "expr": "(\n(\n(sum(kube_pod_status_phase{pod=~\"$executor\",phase=\"Pending\"}*1)by(pod)) + (sum(kube_pod_status_phase{pod=~\"$executor\",phase=\"Running\"}*2)by(pod)) +\n(sum(kube_pod_status_phase{pod=~\"$executor\",phase=\"Succeeded\"}*3)by(pod)) +\n(sum(kube_pod_status_phase{pod=~\"$executor\",phase=\"Unknown\"}*4)by(pod)) +\n(sum(kube_pod_status_phase{pod=~\"$executor\",phase=\"Failed\"}*5)by(pod))\n)\nand on (pod)\nkube_pod_info{created_by_name=\"$Pod\"}\n)\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Driver and Job Runner Pod State Timeline",
     "type": "state-timeline",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "scalar(kube_pod_status_phase{pod=\"$Pod\", phase=\"Failed\"}*5) + \nscalar(kube_pod_status_phase{pod=\"$Pod\", phase=\"Pending\"}*3) + \nscalar(kube_pod_status_phase{pod=\"$Pod\", phase=\"Running\"}*2) + \nscalar(kube_pod_status_phase{pod=\"$Pod\", phase=\"Succeeded\"}*4) + scalar(kube_pod_status_phase{pod=\"$Pod\", phase=\"Unknown\"}*1)\n\n",
       "legendFormat": "Driver"
      },
      {
       "expr": "scalar(kube_pod_status_phase{pod=\"$job_runner_pod\", phase=\"Failed\"}*5) + \nscalar(kube_pod_status_phase{pod=\"$job_runner_pod\", phase=\"Pending\"}*3) + \nscalar(kube_pod_status_phase{pod=\"$job_runner_pod\", phase=\"Running\"}*2) + \nscalar(kube_pod_status_phase{pod=\"$job_runner_pod\", phase=\"Succeeded\"}*4) + scalar(kube_pod_status_phase{pod=\"$job_runner_pod\", phase=\"Unknown\"}*1)",
       "legendFormat": "Job Runner"
      }
     ]
    }
   ]
  }
 ]
}